Week 4 - Authorization
malcolmrjones/step pull request #11
Opened 2020-06-09 19:21 UTC by malcolmrjones

Implemented authorization for the comments feature. Uses AppEngine's User API. Also update the styling of the comment section

2020-06-09 19:32 UTC, brucezheng approved these changes
Good job! Just have a few formatting issues to resolve.

2020-06-09 19:32 UTC, brucezheng commented on portfolio/src/main/java/com/google/sps/data/Comment.java
> +}
Nit: Add newline

2020-06-09 19:32 UTC, brucezheng commented on portfolio/src/main/webapp/script.js
> +    if (displayName === "") displayName =  comment["authorEmail"];
Nit: Extra space between ```=``` and ```comment```

2020-06-09 19:32 UTC, brucezheng commented on portfolio/src/main/webapp/script.js
> + * @param {!string} content
For ```string``` and ```number```, you do not need to use ```!``` to indicate non-nullity.

2020-06-09 19:32 UTC, brucezheng commented on portfolio/src/main/webapp/script.js
> +    + commentDate.getSeconds();
When line wrapping, line break should come _after_ the operator.

https://google.github.io/styleguide/jsguide.html#formatting-where-to-break

2020-06-09 20:50 UTC, ccyang314 requested changes

2020-06-09 20:50 UTC, ccyang314 commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatusServlet.java
> +}
nit: add a new line at the end of each new file.

2020-06-09 20:50 UTC, ccyang314 commented on portfolio/src/main/webapp/style.css
> +  background-color: #F4EBD9;
nit: Looks like some color hex code are uppercase and some of them are lower cases. Could you make them consistent?

2020-06-10 18:14 UTC, ccyang314 approved these changes
LGTM

2020-06-10 18:45 UTC, merged