Week 3 - Step 4 - Using Forms and POST
malcolmrjones/step pull request #6
Opened 2020-06-02 16:01 UTC by malcolmrjones

2020-06-02 16:20 UTC, brucezheng approved these changes

2020-06-02 16:20 UTC, brucezheng commented on portfolio/src/main/webapp/index.html
> +            <p>Web app that provides recipe recommendations based off of ingredient preferences. Techk Stack: HTML, CSS, JavaScript, Django Web Framework</p>
Nit: Tech Stack

2020-06-02 16:33 UTC, ccyang314 commented on portfolio/src/main/webapp/index.html
> +          Currently I am studying computer science at North Carolina Agricultural and Technical State Universty.
nit: typo `University`

2020-06-02 16:36 UTC, ccyang314 requested changes

2020-06-02 16:36 UTC, ccyang314 commented on portfolio/src/main/webapp/index.html
> +          Currently I am studying computer science at North Carolina Agricultural and Technical State Universty.
nit: typo `University`

2020-06-02 16:36 UTC, ccyang314 commented on portfolio/src/main/webapp/script.js
> +function handleGreeting(response) {
nit: add JS function comment to all the new functions included in this PR. 

https://google.github.io/styleguide/jsguide.html#jsdoc-method-and-function-comments

2020-06-03 17:41 UTC, ccyang314 approved these changes
LGTM. Thanks! 

For newer PRs, try to merge to previous step's branch instead of master branch to avoid noisy diffs.

2020-06-03 17:53 UTC, merged